Repository hmcts/fis-ds-web, pull requests merged in 2022-06, with the labels that each got.

#160 Fix idam issue for pr
  charts/fis-ds-web/Chart.yaml
  charts/fis-ds-web/values.aat.template.yaml
  charts/fis-ds-web/values.preview.template.yaml
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-160

#165 Update values.aat.template.yaml
  charts/fis-ds-web/values.aat.template.yaml
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-165

#153 Collect Optional Email from Applicant
  codecept.conf.js
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/resources/email-address/translation.json
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/email-address/content.test.ts
  src/main/steps/edge-case/email-address/content.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/EmailAddress.page.js
  src/test/e2e/pages/UploadDocuments.page.js
  src/test/e2e/tests/SubmitApplication_test.js
  yarn-audit-known-issues
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-153

#162 Feature/isdb 235
  codecept.conf.js
  src/main/app/case/case.ts
  src/main/resources/contact-details/translation.json
  src/main/steps/edge-case/contact-details/content.test.ts
  src/main/steps/edge-case/contact-details/content.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/ContactNumbers.page.js
  src/test/e2e/tests/SubmitApplication_test.js
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-162

#164 Feature/document upload refactor
  config/default.yaml
  config/development.yaml
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/modules/fileupload/index.ts
  src/main/modules/timeouts/index.ts
  src/main/resources/common/translation.json
  src/main/steps/edge-case/upload-additional-documents/template.njk
  src/main/steps/edge-case/upload-additional-documents/uploadDocPostController.ts
  src/main/steps/edge-case/upload-your-documents/template.njk
  src/main/steps/edge-case/upload-your-documents/uploadDocPostController.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-164

#169 Feature/ISDB 241 - Check your answers
  codecept.conf.js
  src/main/app/case/answers/formatDate.ts
  src/main/app/case/case.ts
  src/main/app/case/formatter/address.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/modules/fileupload/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/resources/check-your-answers/translation.json
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/edge-case/check-your-answers/content.test.ts
  src/main/steps/edge-case/check-your-answers/content.ts
  src/main/steps/edge-case/check-your-answers/form.njk
  src/main/steps/edge-case/check-your-answers/template.njk
  src/main/steps/edge-case/check-your-answers/utils.test.ts
  src/main/steps/edge-case/check-your-answers/utils.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/upload-additional-documents/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-additional-documents/uploadDocPostController.ts
  src/main/steps/edge-case/upload-your-documents/uploadDocPostController.test.ts
  src/main/steps/edge-case/user-role/userRolePostController.ts
  src/main/steps/error/error.controller.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/AddressWithPostCode.page.js
  src/test/e2e/pages/CheckYourAnswers.page.js
  src/test/e2e/pages/UploadDocuments.page.js
  src/test/e2e/tests/SubmitApplication_test.js
  src/test/unit/utils/mockUserCase.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-169

#170 Feature/isdb 263 and isb 255 getting started
  config/default.yaml
  config/development.yaml
  src/main/resources/check-your-answers/translation.json
  src/main/resources/landing/translation.json
  src/main/routes/authless/controllers/landing.ts
  src/main/steps/edge-case/check-your-answers/utils.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-170

#167 ISDB-238:
  config/default.yaml
  config/development.yaml
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/case/to-api-format.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/resources/contact-details/translation.json
  src/main/resources/email-address/translation.json
  src/main/resources/full-name/translation.json
  src/main/steps/edge-case/contact-details/content.test.ts
  src/main/steps/edge-case/contact-details/content.ts
  src/main/steps/edge-case/email-address/content.test.ts
  src/main/steps/edge-case/email-address/content.ts
  src/main/steps/edge-case/full-name/content.test.ts
  src/main/steps/edge-case/full-name/content.ts
  src/test/e2e/crossbrowser/supportedBrowsers.js
  src/test/e2e/pages/ApplytoApplicant.page.js
  src/test/e2e/pages/ContactNumbers.page.js
  src/test/e2e/pages/EmailAddress.page.js
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-167

#174 ISDB 259 - first name, last name and email changes
  config/default.yaml
  config/development.yaml
  src/main/app/case/CaseApi.ts
  src/main/app/case/answers/formatDate.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/GetController.ts
  src/main/modules/health/index.ts
  src/main/modules/oidc/index.ts
  src/main/resources/user-role/translation.json
  src/main/steps/common/constants/apiConstants.ts
  src/main/steps/common/constants/commonConstants.ts
  src/main/steps/edge-case/check-your-answers/utils.ts
  src/main/steps/edge-case/upload-additional-documents/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-additional-documents/uploadDocPostController.ts
  src/main/steps/edge-case/upload-your-documents/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-your-documents/uploadDocPostController.ts
  src/main/steps/edge-case/user-role/UserRolePostController.test.ts
  src/main/steps/edge-case/user-role/content.test.ts
  src/main/steps/edge-case/user-role/content.ts
  src/main/steps/edge-case/user-role/template.njk
  src/main/steps/edge-case/user-role/userRolePostController.ts
  src/test/e2e/pages/DetermineApplicantRole.page.js
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-174

#180 Refactoring/update case and attach documents
  Jenkinsfile_CNP
  config/default.yaml
  config/development.yaml
  src/main/app/case/CaseApi.ts
  src/main/steps/edge-case/upload-additional-documents/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-additional-documents/uploadDocPostController.ts
  src/main/steps/edge-case/upload-your-documents/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-your-documents/uploadDocPostController.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-180

#173 Feature/ISBD 257 - Cookies Preferences
  config/default.yaml
  config/development.yaml
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/assets/js/cookie.ts
  src/main/resources/cookies/translation.json
  src/main/resources/upload-addtional-documents/translation.json
  src/main/steps/common/constants/commonConstants.ts
  src/main/steps/cookie-banner/template.njk
  src/main/steps/edge-case/cookies/content.test.ts
  src/main/steps/edge-case/cookies/content.ts
  src/main/steps/edge-case/cookies/template.njk
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/upload-your-documents/uploadDocPostController.ts
  src/main/steps/urls.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-173
