Repository hmcts/fis-ds-web, pull requests merged in 2022-07, with the labels that each got.

#181 disabled full funtional from nightly and added cross browser script
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-181

#183 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-183

#179 Feature/isdb 217 application submitted
  codecept.conf.js
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/parser.ts
  src/main/resources/application-submitted/translation.json
  src/main/resources/statement-of-truth/translation.json
  src/main/steps/edge-case/application-submitted/content.test.ts
  src/main/steps/edge-case/application-submitted/content.ts
  src/main/steps/edge-case/application-submitted/template.njk
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/statement-of-truth/content.test.ts
  src/main/steps/edge-case/statement-of-truth/content.ts
  src/main/steps/edge-case/statement-of-truth/template.njk
  src/main/steps/urls.ts
  src/test/e2e/pages/StatementOfTruth.page.js
  src/test/e2e/pages/ThankYou.page.js
  src/test/e2e/tests/SubmitApplication_test.js
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-179

#182 ISDB-287 - Upload document screen changes
  config/default.yaml
  config/development.yaml
  saucelabs.conf.js
  src/main/resources/upload-your-documents/translation.json
  src/main/steps/edge-case/upload-your-documents/uploadDocPostController.test.ts
  src/main/steps/edge-case/upload-your-documents/uploadDocPostController.ts
  src/test/e2e/pages/AdditionalDocuments.page.js
  src/test/e2e/pages/UploadDocuments.page.js
  src/test/e2e/tests/smoke_test.js
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-182

#188 cross browser test fixes saucelabs
  Jenkinsfile_nightly
  src/test/e2e/pages/Adoption.page.js
  src/test/e2e/pages/Contactdetails.page.js
  src/test/e2e/pages/Family.page.js
  src/test/e2e/pages/ReviewPayment.page.js
  src/test/e2e/tests/SubmitApplication_test.js
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-188

#190 further upd to cross browser test
  Jenkinsfile_nightly
  yarn-audit-known-issues
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-190

#189 Updated the contents of the screen
  src/main/resources/check-your-answers/translation.json
  src/main/resources/contact-details/translation.json
  src/main/resources/contact-preferences/translation.json
  src/main/resources/email-address/translation.json
  src/main/resources/full-name/translation.json
  src/main/resources/landing/translation.json
  src/main/resources/statement-of-truth/translation.json
  src/main/resources/upload-addtional-documents/translation.json
  src/main/resources/upload-your-documents/translation.json
  src/main/resources/user-role/translation.json
  src/main/routes/authless/views/landing.njk
  src/main/steps/edge-case/check-your-answers/form.njk
  src/main/steps/edge-case/contact-details/content.test.ts
  src/main/steps/edge-case/contact-details/content.ts
  src/main/steps/edge-case/contact-preferences/content.ts
  src/main/steps/edge-case/email-address/content.test.ts
  src/main/steps/edge-case/upload-additional-documents/content.test.ts
  src/main/steps/edge-case/upload-additional-documents/template.njk
  src/main/steps/edge-case/upload-your-documents/template.njk
  src/test/e2e/fixtures/content/AdditionalDocuments_content.js
  src/test/e2e/fixtures/content/ApplicantName_content.js
  src/test/e2e/fixtures/content/CheckYourAnswers_content.js
  src/test/e2e/fixtures/content/ContactNumber_content.js
  src/test/e2e/fixtures/content/ContactPreferences_content.js
  src/test/e2e/fixtures/content/DetermineRole_content.js
  src/test/e2e/fixtures/content/EmailAddress_content.js
  src/test/e2e/fixtures/content/LandingPage_content.js
  src/test/e2e/fixtures/content/StatementOfTruth_content.js
  src/test/e2e/fixtures/content/UploadDocuments_content.js
  src/test/e2e/pages/AdditionalDocuments.page.js
  src/test/e2e/pages/ApplytoApplicant.page.js
  src/test/e2e/pages/CheckYourAnswers.page.js
  src/test/e2e/pages/ContactNumbers.page.js
  src/test/e2e/pages/ContactPreference.page.js
  src/test/e2e/pages/DetermineApplicantRole.page.js
  src/test/e2e/pages/EmailAddress.page.js
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/pages/StatementOfTruth.page.js
  src/test/e2e/pages/UploadDocuments.page.js
  yarn-audit-known-issues
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-189

#193 saucelab def tunnel disabled
  Jenkinsfile_nightly
  saucelabs.conf.js
  src/test/e2e/crossbrowser/supportedBrowsers.js
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-193

#194 fix eventName passing from UI
  src/main/app/case/CaseApi.ts
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-194

#192 Feature/isdb 316
  src/main/routes.ts
  src/main/steps/accessibility-statement/content.test.ts
  src/main/steps/accessibility-statement/content.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/accessibility-statement/get.ts
  src/main/steps/accessibility-statement/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/page.njk
  src/main/steps/contact-us/content.test.ts
  src/main/steps/contact-us/content.ts
  src/main/steps/contact-us/get.test.ts
  src/main/steps/contact-us/get.ts
  src/main/steps/contact-us/template.njk
  src/main/steps/privacy-policy/content.test.ts
  src/main/steps/privacy-policy/content.ts
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/privacy-policy/get.ts
  src/main/steps/privacy-policy/template.njk
  src/main/steps/terms-and-conditions/content.test.ts
  src/main/steps/terms-and-conditions/content.ts
  src/main/steps/terms-and-conditions/get.test.ts
  src/main/steps/terms-and-conditions/get.ts
  src/main/steps/terms-and-conditions/template.njk
  src/main/steps/urls.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-192

#195 enable nightly functional tests
  Jenkinsfile_nightly
  codecept.conf.js
  saucelabs.conf.js
  yarn-audit-known-issues
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-195

#197 disable nightly functional tests
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-197

#198 vulnerabilities addition
  charts/fis-ds-web/Chart.yaml
  yarn-audit-known-issues
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-198

#200 yarn audit issues update
  yarn-audit-known-issues
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-200

#201 Update README.md
  README.md
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-201
