Repository hmcts/fis-ds-web, pull requests merged in 2022-03, with the labels that each got.

#28 sync demo env with master branch for ds-ui
  Jenkinsfile_CNP
Labels: ns:ds, prd:ds, rel:ds-ui-pr-28

#42 replace idam-secret with idam-ui-secret
  Jenkinsfile_nightly
  charts/ds-ui/Chart.yaml
  charts/ds-ui/values.yaml
  infrastructure/main.tf
  src/main/modules/properties-volume/index.ts
Labels: ns:ds, prd:ds, rel:ds-ui-pr-42

#43 Feature/idam secret update
  charts/ds-ui/Chart.yaml
  charts/ds-ui/values.yaml
  src/main/modules/session/index.ts
Labels: ns:ds, prd:ds, rel:ds-ui-pr-43

#52 Feature/isdb 96 backlink issue
  src/main/steps/edge-case/adoption-application-type/template.njk
  src/main/steps/edge-case/date-of-birth/template.njk
  src/main/steps/edge-case/full-name/template.njk
  webpack.config.js
  webpack/hmctsFrontend.js
  webpack/htmlWebpack.js
Labels: ns:ds, prd:ds, rel:ds-ui-pr-52

#55 smoketest fix for AAT env
  Jenkinsfile_CNP
  src/test/config.js
Labels: ns:ds, prd:ds, rel:ds-ui-pr-55

#57 merge with master branch
  package.json
  src/main/steps/common/components/full-name.ts
  src/main/steps/common/form/form.njk
  src/main/steps/edge-case/full-name/content.test.ts
  src/main/steps/edge-case/full-name/content.ts
  src/main/steps/edge-case/full-name/template.njk
  src/main/steps/edge-case/private-law-application-type/content.test.ts
  src/main/steps/edge-case/private-law-application-type/content.ts
  src/main/steps/errorMesages.ts
Labels: ns:ds, prd:ds, rel:ds-ui-pr-57

#77 isdb-60 and 61
  codecept.conf.js
  src/test/e2e/pages/ApplytoApplicant.page.js
  src/test/e2e/pages/Family.page.js
  src/test/e2e/pages/LandingPage.js
  src/test/e2e/tests/SubmitApplication_test.js
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-77

#84 isdb-62 changes
  codecept.conf.js
  src/test/e2e/pages/Adoption.page.js
  src/test/e2e/tests/SubmitApplication_test.js
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-84

#62 title bar fix
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.ts
  src/main/steps/edge-case/full-name/content.ts
Labels: ns:ds, prd:ds, rel:ds-ui-pr-62

#70 ISDB-55 - Address look up adn select screen
  charts/fis-ds-web/Chart.yaml
  charts/fis-ds-web/values.yaml
  codecept.conf.js
  src/main/app/address/AddressLookupPostControllerBase.test.ts
  src/main/app/address/AddressLookupPostControllerBase.ts
  src/main/app/address/SelectAddressPostControllerBase.test.ts
  src/main/app/address/SelectAddressPostControllerBase.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.ts
  src/main/app/postcode/postcode-lookup-api.test.ts
  src/main/app/postcode/postcode-lookup-api.ts
  src/main/modules/oidc/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/components/address-international.test.ts
  src/main/steps/common/components/address-lookup.test.ts
  src/main/steps/common/components/address-lookup.ts
  src/main/steps/common/components/address-manual.test.ts
  src/main/steps/common/components/address-manual.ts
  src/main/steps/common/components/address-select.test.ts
  src/main/steps/common/components/address-select.ts
  src/main/steps/edge-case/address/lookup/AddressLookupPostController.test.ts
  src/main/steps/edge-case/address/lookup/AddressLookupPostController.ts
  src/main/steps/edge-case/address/lookup/content.test.ts
  src/main/steps/edge-case/address/lookup/content.ts
  src/main/steps/edge-case/address/manual/content.test.ts
  src/main/steps/edge-case/address/manual/content.ts
  src/main/steps/edge-case/address/select/SelectAddressPostController.test.ts
  src/main/steps/edge-case/address/select/SelectAddressPostController.ts
  src/main/steps/edge-case/address/select/content.test.ts
  src/main/steps/edge-case/address/select/content.ts
  src/main/steps/edge-case/address/select/form.njk
  src/main/steps/edge-case/date-of-birth/content.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/test/e2e/pages/AddressWithPostCode.page.js
  src/test/e2e/pages/DateOfBirth.page.js
  src/test/e2e/tests/SubmitApplication_test.js
  src/test/unit/utils/mockPostcodeResponses.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-70

#76 feat: date of birth changes(ISDB-64)
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/edge-case/date-of-birth/content.test.ts
  src/main/steps/edge-case/date-of-birth/content.ts
  src/main/steps/edge-case/date-of-birth/template.njk
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-76

#86 isdb-65 changes
  codecept.conf.js
  src/test/e2e/pages/Adoption.page.js
  src/test/e2e/pages/Contactdetails.page.js
  src/test/e2e/tests/SubmitApplication_test.js
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-86
