Repository hmcts/fis-ds-web, pull requests merged in 2022-05, with the labels that each got.

#130 screen chages of 121
  codecept.conf.js
  src/test/e2e/tests/SubmitApplication_test.js
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-130

#121 Sequence added for upload documents
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/upload-your-documents/content.ts
  src/main/steps/edge-case/upload-your-documents/uploadDocPostController.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-121

#139 to check deployment issue. dummy change, need to revert.
  src/main/steps/edge-case/full-name/content.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-139

#138 feat: implement user-role screen(ISDB-214)
  .gitignore
  codecept.conf.js
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/modules/oidc/index.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/user-role/UserRolePostController.test.ts
  src/main/steps/edge-case/user-role/content.test.ts
  src/main/steps/edge-case/user-role/content.ts
  src/main/steps/edge-case/user-role/userRolePostController.ts
  src/main/steps/errorMesages.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/DetermineApplicantRole.page.js
  src/test/e2e/tests/SubmitApplication_test.js
  test-results/result.xml
  yarn.lock
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-138

#147 ISDB-209 - Contact Preferences screen changes
  .gitignore
  codecept.conf.js
  src/main/app/case/definition.ts
  src/main/public/img/favicon.ico
  src/main/resources/contact-preferences/translation.json
  src/main/steps/edge-case/contact-preferences/content.test.ts
  src/main/steps/edge-case/contact-preferences/content.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/urls.ts
  src/test/e2e/pages/ContactPreference.page.js
  src/test/e2e/tests/SubmitApplication_test.js
  test-results/result.xml
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-147
