Repository hmcts/fis-ds-web, pull requests merged in 2022-04, with the labels that each got.

#92 fix title bar issue - back button
  src/main/app/address/AddressLookupPostControllerBase.ts
  src/main/app/address/SelectAddressPostControllerBase.ts
  src/main/app/controller/PostController.ts
  src/main/steps/edge-case/contact-details/content.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-92

#95 enable e2e tests
  Jenkinsfile_CNP
  package.json
  src/test/e2e/pages/AddressWithPostCode.page.js
  src/test/e2e/pages/Adoption.page.js
  src/test/e2e/pages/DateOfBirth.page.js
  src/test/e2e/tests/SubmitApplication_test.js
  yarn-audit-known-issues
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-95

#99 fix: validation issue(ISDB-126)
  src/main/app/form/validation.ts
  src/main/steps/edge-case/contact-details/content.ts
  yarn-audit-known-issues
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-99

#97 feat: fee screen and api integration(ISDB-121)
  config/default.yaml
  src/main/app/fee/fee-lookup-api.test.ts
  src/main/app/fee/fee-lookup-api.ts
  src/main/assets/js/go-back.ts
  src/main/steps/constants.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/payment/pay-your-fee/content.test.ts
  src/main/steps/edge-case/payment/pay-your-fee/content.ts
  src/main/steps/edge-case/payment/pay-your-fee/get.test.ts
  src/main/steps/edge-case/payment/pay-your-fee/get.ts
  src/main/steps/edge-case/payment/pay-your-fee/template.njk
  src/main/steps/urls.ts
  src/test/unit/utils/mockFeeLookupResponses.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-97

#103 fixed full functional test iteration
  package.json
  src/test/e2e/tests/SubmitApplication_test.js
  test-results/result.xml
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-103

#109 suppress known vulnerability warning
  yarn-audit-known-issues
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-109

#111 Feature/isb 113 document uploading
  .eslintrc.js
  config/default.yaml
  config/development.yaml
  package.json
  sonar-project.properties
  src/main/app/case/definition.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/app/document/DocumentManagementClient.test.ts
  src/main/app/document/DocumentManagementClient.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/app/document/__mocks__/DocumentManagementClient.ts
  src/main/app/form/validation.ts
  src/main/app/rpe/RpeApi.ts
  src/main/assets/js/upload-manager/FileUploadEvents.ts
  src/main/assets/js/upload-manager/UploadedFiles.ts
  src/main/assets/js/upload-manager/index.ts
  src/main/assets/js/upload-manager/updateFileList.ts
  src/main/assets/scss/upload-documents.scss
  src/main/modules/fileupload/index.ts
  src/main/routes.ts
  src/main/server.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/upload-your-documents/content.test.ts
  src/main/steps/edge-case/upload-your-documents/content.ts
  src/main/steps/edge-case/upload-your-documents/template.njk
  src/main/steps/edge-case/upload-your-documents/uploadDocPostController.ts
  src/main/steps/urls.ts
  src/test/unit/utils/languageAssertions.ts
  yarn.lock
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-111

#119 upload document changes
  codecept.conf.js
  src/test/e2e/pages/UploadDocuments.page.js
  src/test/e2e/tests/SubmitApplication_test.js
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-119

#118 added file handler comments
  config/default.yaml
  config/development.yaml
  src/main/steps/edge-case/upload-your-documents/template.njk
  src/main/steps/edge-case/upload-your-documents/uploadDocPostController.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-118

#120 added updated BOT PR
  package.json
  yarn.lock
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-120
