Repository hmcts/fis-ds-web, pull requests merged in 2025-02, with the labels that each got.

#360 PRL-3938: Rule to charge Edge case applications submitted by users
  package.json
  src/main/app/auth/user/oidc.test.ts
  src/main/resources/statement-of-truth/translation.json
  src/main/steps/edge-case/check-your-answers/content.test.ts
  src/main/steps/edge-case/check-your-answers/utils.test.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/select-court/content.test.ts
  src/main/steps/edge-case/select-court/content.ts
  src/main/steps/edge-case/statement-of-truth/content.test.ts
  src/main/steps/edge-case/statement-of-truth/content.ts
  src/main/steps/edge-case/statement-of-truth/routeGuard.test.ts
  src/main/steps/edge-case/statement-of-truth/routeGuard.ts
  src/main/steps/edge-case/statement-of-truth/template.njk
  src/main/steps/edge-case/upload/upload-additional-documents/uploadAdditionalDocumentController.test.ts
  src/main/steps/edge-case/upload/upload-your-documents/uploadDocPostController.test.ts
  src/main/steps/home/get.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-360

#364 GA
  src/main/assets/js/cookie.ts
  src/main/modules/helmet/index.ts
  src/main/steps/common/page.njk
  src/main/steps/common/views/includes/script-ga_tag_manager.njk
  src/main/steps/common/views/includes/script-ga_tag_manager_2.njk
Labels: ns:fis, prd:fis, enable_keep_helm, rel:fis-ds-web-pr-364

#363 testcase
  README.md
  sonar-project.properties
  src/main/app/address/AddressLookupPostControllerBase.test.ts
  src/main/app/address/SelectAddressPostControllerBase.test.ts
  src/main/app/address/SelectAddressPostControllerBase.ts
  src/main/app/auth/user/oidc.test.ts
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/api-utility.test.ts
  src/main/app/case/formatter/address.test.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/validation.test.ts
  src/main/resources/landing/translation.json
  src/main/routes/authless/views/landing.njk
  src/main/steps/edge-case/address/select/content.test.ts
  src/main/steps/edge-case/check-your-answers/content.test.ts
  src/main/steps/edge-case/check-your-answers/utils.test.ts
  src/main/steps/edge-case/contact-details/content.test.ts
  src/main/steps/edge-case/contact-details/postController.test.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/full-name/content.test.ts
  src/main/steps/edge-case/help-with-fee/content.test.ts
  src/main/steps/edge-case/pay-your-fee/routeGuard.test.ts
  src/main/steps/edge-case/select-court/content.test.ts
  src/main/steps/edge-case/select-court/routeGuard.test.ts
  src/main/steps/edge-case/type-of-application/content.test.ts
  src/main/steps/edge-case/type-of-application/routeGuard.test.ts
  src/main/steps/edge-case/upload/upload-additional-documents/uploadAdditionalDocumentController.test.ts
  src/main/steps/edge-case/upload/upload-your-documents/uploadDocPostController.test.ts
  src/main/steps/edge-case/user-role/UserRolePostController.test.ts
  src/main/steps/edge-case/user-role/content.test.ts
  src/main/steps/home/get.test.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-363

#362 PRL-6880: Fix sonar issues
  sonar-project.properties
  src/main/app/address/AddressLookupPostControllerBase.ts
  src/main/app/address/SelectAddressPostControllerBase.ts
  src/main/app/auth/service/get-service-auth-token.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/api-utility.test.ts
  src/main/app/case/definition.ts
  src/main/app/case/formatter/address.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.ts
  src/main/app/form/parser.test.ts
  src/main/app/form/parser.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/assets/js/session-timeout.ts
  src/main/modules/helmet/index.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/error/summary.njk
  src/main/steps/common/form/form.njk
  src/main/steps/edge-case/check-your-answers/content.ts
  src/main/steps/edge-case/check-your-answers/utils.test.ts
  src/main/steps/edge-case/check-your-answers/utils.ts
  src/main/steps/edge-case/pay-your-fee/PayAndSubmitPostController.test.ts
  src/main/steps/edge-case/pay-your-fee/PayAndSubmitPostController.ts
  src/main/steps/edge-case/pay-your-fee/content.test.ts
  src/main/steps/edge-case/pay-your-fee/content.ts
  src/main/steps/edge-case/pay-your-fee/routeGuard.ts
  src/main/steps/edge-case/payments/paymentController.test.ts
  src/main/steps/edge-case/payments/paymentController.ts
  src/main/steps/edge-case/payments/paymentHelper.ts
  src/main/steps/edge-case/statement-of-truth/routeGuard.test.ts
  src/main/steps/edge-case/statement-of-truth/routeGuard.ts
  src/main/steps/edge-case/upload/upload-your-documents/uploadDocPostController.ts
  src/main/steps/edge-case/upload/utils.ts
  src/main/steps/edge-case/user-role/UserRolePostController.test.ts
  src/main/steps/edge-case/user-role/content.test.ts
  src/main/steps/edge-case/user-role/userRolePostController.ts
  src/main/steps/index.ts
Labels: ns:fis, prd:fis, rel:fis-ds-web-pr-362

#370 Fix docker build issue
  .dockerignore
  .yarn/releases/yarn-3.5.1.cjs
  .yarn/releases/yarn-3.8.1.cjs
  .yarn/releases/yarn-4.6.0.cjs
  .yarnrc.yml
  Dockerfile
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:fis, prd:fis, enable_keep_helm, rel:fis-ds-web-pr-370

#369 PRL-6986: Change content on case creation screens
  config/default.yaml
  src/main/app/case/api-utility.test.ts
  src/main/app/case/api-utility.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/resources/check-your-answers/translation.json
  src/main/resources/contact-details/translation.json
  src/main/resources/contact-preferences/translation.json
  src/main/resources/date-of-birth/translation.json
  src/main/resources/email-address/translation.json
  src/main/resources/full-name/translation.json
  src/main/resources/landing/translation.json
  src/main/resources/manual-address/translation.json
  src/main/resources/pay-your-fee/translation.json
  src/main/resources/select-address/translation.json
  src/main/resources/type-of-application/translation.json
  src/main/resources/upload-additional-documents/translation.json
  src/main/resources/upload-your-documents/translation.json
  src/main/resources/user-role/translation.json
  src/main/steps/edge-case/check-your-answers/content.test.ts
  src/main/steps/edge-case/check-your-answers/content.ts
  src/main/steps/edge-case/check-your-answers/utils.ts
  src/main/steps/edge-case/contact-details/content.test.ts
  src/main/steps/edge-case/contact-details/content.ts
  src/main/steps/edge-case/contact-details/postController.test.ts
  src/main/steps/edge-case/contact-details/postController.ts
  src/main/steps/edge-case/contact-preferences/content.test.ts
  src/main/steps/edge-case/contact-preferences/content.ts
  src/main/steps/edge-case/date-of-birth/content.ts
  src/main/steps/edge-case/date-of-birth/template.njk
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/select-court/routeGuard.ts
  src/main/steps/edge-case/statement-of-truth/content.ts
  src/main/steps/edge-case/statement-of-truth/routeGuard.ts
  src/main/steps/edge-case/type-of-application/content.test.ts
  src/main/steps/edge-case/type-of-application/content.ts
  src/main/steps/edge-case/type-of-application/routeGuard.test.ts
  src/main/steps/edge-case/type-of-application/routeGuard.ts
  src/main/steps/edge-case/upload/upload-your-documents/content.ts
  src/main/steps/edge-case/upload/upload-your-documents/template.njk
  src/main/steps/edge-case/upload/utils.test.ts
  src/main/steps/edge-case/upload/utils.ts
  src/main/steps/edge-case/user-role/UserRolePostController.test.ts
  src/main/steps/edge-case/user-role/content.test.ts
  src/main/steps/edge-case/user-role/content.ts
  src/main/steps/edge-case/user-role/userRolePostController.ts
  src/main/steps/edge-case/util.ts
  src/main/steps/urls.ts
  src/test/unit/utils/mockUserCase.ts
Labels: ns:fis, prd:fis, enable_keep_helm, rel:fis-ds-web-pr-369

#373 PRL-6990: Add other C1 application types
  src/main/app/case/definition.ts
  src/main/resources/check-your-answers/translation.json
  src/main/resources/type-of-application/translation.json
  src/main/steps/edge-case/check-your-answers/form.njk
  src/main/steps/edge-case/type-of-application/content.test.ts
  src/main/steps/edge-case/type-of-application/content.ts
Labels: ns:fis, prd:fis, enable_keep_helm, rel:fis-ds-web-pr-373

#372 PRL-6989: Add new HWF screens
  src/main/app/case/api-utility.test.ts
  src/main/app/case/api-utility.ts
  src/main/app/case/case.ts
  src/main/app/form/Form.ts
  src/main/resources/application-submitted/translation.json
  src/main/resources/check-your-answers/translation.json
  src/main/resources/fees-applied/translation.json
  src/main/resources/help-with-fee/translation.json
  src/main/resources/landing/translation.json
  src/main/resources/need-help-with-fees/translation.json
  src/main/resources/pay-your-fee/translation.json
  src/main/routes/authless/views/landing.njk
  src/main/steps/common/form/fields/textAndHtml.njk
  src/main/steps/common/form/form.njk
  src/main/steps/edge-case/application-submitted/content.test.ts
  src/main/steps/edge-case/application-submitted/content.ts
  src/main/steps/edge-case/application-submitted/template.njk
  src/main/steps/edge-case/check-your-answers/content.ts
  src/main/steps/edge-case/check-your-answers/utils.test.ts
  src/main/steps/edge-case/check-your-answers/utils.ts
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/edge-case/edgecaseSequence.ts
  src/main/steps/edge-case/help-with-fee/content.test.ts
  src/main/steps/edge-case/help-with-fee/content.ts
  src/main/steps/edge-case/help-with-fee/template.njk
  src/main/steps/edge-case/help-with-fees/fees-applied/content.test.ts
  src/main/steps/edge-case/help-with-fees/fees-applied/content.ts
  src/main/steps/edge-case/help-with-fees/fees-applied/routeGuard.test.ts
  src/main/steps/edge-case/help-with-fees/fees-applied/routeGuard.ts
  src/main/steps/edge-case/help-with-fees/fees-applied/template.njk
  src/main/steps/edge-case/help-with-fees/need-help-with-fees/content.test.ts
  src/main/steps/edge-case/help-with-fees/need-help-with-fees/content.ts
  src/main/steps/edge-case/help-with-fees/need-help-with-fees/routeGuard.test.ts
  src/main/steps/edge-case/help-with-fees/need-help-with-fees/routeGuard.ts
  src/main/steps/edge-case/help-with-fees/need-help-with-fees/template.njk
  src/main/steps/edge-case/pay-your-fee/PayAndSubmitPostController.test.ts
  src/main/steps/edge-case/pay-your-fee/PayAndSubmitPostController.ts
  src/main/steps/edge-case/pay-your-fee/content.test.ts
  src/main/steps/edge-case/pay-your-fee/content.ts
  src/main/steps/edge-case/pay-your-fee/routeGuard.ts
  src/main/steps/edge-case/pay-your-fee/template.njk
  src/main/steps/edge-case/statement-of-truth/content.ts
  src/main/steps/edge-case/statement-of-truth/routeGuard.test.ts
  src/main/steps/edge-case/statement-of-truth/routeGuard.ts
  src/main/steps/edge-case/upload/upload-additional-documents/uploadAdditionalDocumentController.test.ts
  src/main/steps/edge-case/upload/upload-additional-documents/uploadAdditionalDocumentPostController.ts
  src/main/steps/urls.ts
Labels: ns:fis, prd:fis, enable_keep_helm, rel:fis-ds-web-pr-372
